export const CardData = [
    {
        id: '01',
        src: "public/images/foods/Chicken_Burger.jpg",
        alt: "this is alt text",
        title: "Chicken Burger",
        price: 12,
        ratting: 4,
    },
    {
        id: '02',
        src: "public/images/foods/Chicken_Cheese_Pizza.jpg",
        alt: "this is alt text",
        title: "Chicken Cheese Pizza",
        price: 15,
        ratting: 5,
    },
    {
        id: '03',
        src: "public/images/foods/Chicken_Fry.jpg",
        alt: "this is alt text",
        title: "Chicken Fry",
        price: 32,
        ratting: 2,
    },
    {
        id: '04',
        src: "public/images/foods/Chicken_Sandwich.jpg",
        alt: "this is alt text",
        title: "Chicken Sandwich",
        price: 7,
        ratting: 5,
    },
    {
        id: '05',
        src: "public/images/foods/Fry_Nurger.jpg",
        alt: "this is alt text",
        title: "Fry Nurger",
        price: 10,
        ratting: 5,
    },
    {
        id: '06',
        src: "public/images/foods/Grill_Chicken.jpg",
        alt: "this is alt text",
        title: "Grill Chicken",
        price: 3,
        ratting: 5,
    },
    {
        id: '07',
        src: "public/images/foods/Pasta.jpg",
        alt: "this is alt text",
        title: "Pasta",
        price: 44,
        ratting: 2,
    },
    {
        id: '08',
        src: "public/images/foods/Seekh_Kebab.jpg",
        alt: "this is alt text",
        title: "Seekh Kebab",
        price: 43,
        ratting: 5,
    }
  ];